# site name
siteName: 李佳芮の博客
shortName: 芮


# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon
favicon: /images/favicon.png
# unique avatar
avatarShow: false
avatarImage: /images/favicon.png

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10


# your site build time or domain buy time
siteBuildingTime: 01/20/2018


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
  chatbot: chatbot
  presentation: presentation
  project: project
  技术随笔: tech
  thought: thought
  读书笔记: reading
  
# Left menu of single pages settings
## Notice: faName is FontAwesome style name
leftPagesMenu:
- uri: about
  title: 关于本站
  faName: fa-user


# cover info config
coverTitle: 时间看得见
coverDescription: 一个现实的理想主义者

# sns url
sns:
  weibo: https://weibo.com/u/2175505900?refer_flag=1001030101_
  weixin: http://blog.botorange.com
  github: https://github.com/lijiarui
  telegram: https://www.jianshu.com/u/ac5aaa7ad293

# your article copyright or content declare
postDeclare: 本文代表个人观点，内容仅供参考。若有不恰当之处，望不吝赐教！

# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: false
  githubID: 6419514
  repo: https://github.com/lijiarui/lijiarui.github.io
  ClientID: 6b95c0bbd207540bc232
  ClientSecret: 78d5e37397020b4a31560a40ca9f67a1bc0c2b1d
  lazy: true

## Comments settings.You can choose only ONE to display.
# disqus shortName,
disqus_shortname: lijiarui

# Analytics
tentcentAnalyticsId:
